name 'reanrepofortesting'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures reanrepofortesting'
long_description 'Installs/Configures reanrepofortesting'
version '0.1.0'
